AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Flutter Follow-Dao on AWS Lambda

Globals:
  Function:
    Timeout: 3

Resources:
  FollowTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Follow"
      AttributeDefinitions:
        - AttributeName: "follower"
          AttributeType: "S"
        - AttributeName: "author"
          AttributeType: "S"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      KeySchema:
        - AttributeName: "follower"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: FollowByAuthorIndex
          KeySchema:
            -
              AttributeName: "author"
              KeyType: "HASH"
          Projection:
            NonKeyAttributes:
              - "follower"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
  FollowDaoRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LogRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:SaveLogEvents
                Resource: "*"
        - PolicyName: DynamoDBFollowRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: !GetAtt FollowTable.Arn
    DependsOn: FollowTable
  FollowDaoGetAllFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getall/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        Flutter:
          Type: Api
          Properties:
            Path: /follow-dao/getAll
            Method: post
      Role: !GetAtt FollowDaoRole.Arn
    DependsOn: FollowDaoRole
  FollowDaoSaveFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: save/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        Flutter:
          Type: Api
          Properties:
            Path: /follow-dao/save
            Method: post
      Role: !GetAtt FollowDaoRole.Arn
    DependsOn: FollowDaoRole
